FROM node:24-alpine AS build-stage

# 设置工作目录
WORKDIR /app

# 先只拷贝 package.json，利用 Docker 缓存机制加速构建
COPY package*.json ./

# 安装依赖 (如果你用 pnpm 或 yarn，请相应修改)

RUN npm install -g pnpm 

RUN pnpm install

# 拷贝所有源代码
COPY . .

# 开始打包 (生成 dist 文件夹)
RUN pnpm run build

# 阶段 2: 运行阶段 (用 Nginx 提供服务)
FROM nginx:stable-alpine AS production-stage

# 1. 把刚才构建阶段生成的 dist 文件夹，复制到 Nginx 的默认目录
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 2. 把我们自定义的 Nginx 配置复制进去，覆盖默认配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]