# docker-compose-infra.yaml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gopher_db
    restart: always
    environment:
      POSTGRES_USER: luckys
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gopher_paste
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - gopher-net  # 加入这个网络

  redis:
    image: redis:alpine
    container_name: gopher_redis
    restart: always 
    command: redis-server --appendonly yes --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - gopher-net  # 加入这个网络
      
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - gopher-net

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro          # 读取进程信息
      - /sys:/host/sys:ro            # 读取系统信息
      - /:/rootfs:ro                 # 读取文件系统信息
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
    networks:
      - gopher-net

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=luckys
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - gopher-net

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - gopher-net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro    # Docker 日志
      - /var/log:/var/log:ro    # 系统日志
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - gopher-net

volumes:
  prometheus_data:
  grafana_data:
  redis_data:
  loki_data:

networks:
  gopher-net:
    external: true  # 声明：这个网络是外部存在的，不要新建，直接连上去！