services:
  user-service:
    image: crpi-owej7l76wqheszs7.cn-hangzhou.personal.cr.aliyuncs.com/luckys_devops/user_service:latest
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      - paste-service

  paste-service:
    image: crpi-owej7l76wqheszs7.cn-hangzhou.personal.cr.aliyuncs.com/luckys_devops/paste_service:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=gopher_redis:6379
    networks:
      - default

  frontend-service:
    image: crpi-owej7l76wqheszs7.cn-hangzhou.personal.cr.aliyuncs.com/luckys_devops/frontend_service:latest
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - user-service
      - paste-service

networks:
  default:
    name: gopher-net
    external: true