services:
  user-service:
    build:
      context: ./backend
      dockerfile: dockerfile.user
    ports:
      - "8081:8080"
    environment:
      - ENV=development
      - SERVER_PORT=8080
      - DB_SOURCE=postgres://luckys:123456@gopher_db:5432/gopher_paste?sslmode=disable
      - REDIS_ADDR=gopher_redis:6379
      - REDIS_PASSWORD=123456
      - JWT_SECRET=gopherpaste_secret_key
    networks:
      - default
    depends_on:
      - paste-service

  paste-service:
    build:
      context: ./backend
      dockerfile: dockerfile.paste
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - SERVER_PORT=8080
      - DB_SOURCE=postgres://luckys:123456@gopher_db:5432/gopher_paste?sslmode=disable
      - REDIS_ADDR=gopher_redis:6379
      - REDIS_PASSWORD=123456
    networks:
      - default

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - user-service
      - paste-service

networks:
  default:
    name: gopher_network
    external: true
