version: '3.8'

services:
  user-service:
    image: crpi-owej7l76wqheszs7-vpc.cn-hangzhou.personal.cr.aliyuncs.com/luckys_devops/user_service
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      - paste-service

  paste-service:
    image: crpi-owej7l76wqheszs7-vpc.cn-hangzhou.personal.cr.aliyuncs.com/luckys_devops/paste_service
    ports:
      - "8082:8080"
    networks:
      - default

networks:
  default:
    name: gopher-net
    external: true