// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Paste struct {
	ShortLink string
	Content   string
	Language  string
	ExpiresAt sql.NullTime
	CreatedAt time.Time
}
