// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Paste struct {
	ID         int64
	OwnerID    int64
	Title      string
	ShortLink  sql.NullString
	Content    string
	Language   string
	Visibility string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
