// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createPaste = `-- name: CreatePaste :one

INSERT INTO pastes (
  short_link, content, language, expires_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING short_link, content, language, expires_at, created_at
`

type CreatePasteParams struct {
	ShortLink string
	Content   string
	Language  string
	ExpiresAt sql.NullTime
}

// db/query.sql
func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) (Paste, error) {
	row := q.db.QueryRowContext(ctx, createPaste,
		arg.ShortLink,
		arg.Content,
		arg.Language,
		arg.ExpiresAt,
	)
	var i Paste
	err := row.Scan(
		&i.ShortLink,
		&i.Content,
		&i.Language,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaste = `-- name: GetPaste :one
SELECT short_link, content, language, expires_at, created_at FROM pastes
WHERE short_link = $1 LIMIT 1
`

func (q *Queries) GetPaste(ctx context.Context, shortLink string) (Paste, error) {
	row := q.db.QueryRowContext(ctx, getPaste, shortLink)
	var i Paste
	err := row.Scan(
		&i.ShortLink,
		&i.Content,
		&i.Language,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
